### ISSUE TITLE
Research about using Montgomery form in `modexp`

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/zksync_era_precompiles#108]
**Context:** `ModExp.yul`

**Description:**
It is difficult to optimize `mulmod` at a compiler level, so we need to optimize modular multiplications at a Yul level. We need to look if it'd be more efficient to use the Montgomery form even without the algorithm values that could be precomputed with a known modulus, as in the elliptic curve precompiles.

**Recommendation:**

Implement Montgomery Modular Multiplication algorithm. This is done in the elliptic curve precompiles, the only difference is that values like `R2_MOD_P` and `N_PRIME` cannot be precomputed and should be computed after knowing the modulus. Also `R` cannot be $2^{256}$ and we should find a proper `R` for every modulus. I think that we could use $R = 2^{256}$ for a modulus with less than 256 bits.

**Comment by fkrause98** [comment]
There are some approaches for modexp, modexp has the following signature:
```rust
fn modexp(base: BigInt, exp: BigInt, modulo: Int) -> BigInt
```
## Montgomery
The issue with the [Montgomery algorithm](https://www.nayuki.io/page/montgomery-reduction-algorithm) is that we need to precompute a constant $R \in \mathbb{Z}$ such that $R \gt n$ and $gcd(R, n) = 1$ (where n is the modulo argument).
This is fine when we know $n$ beforehand, since we can just choose and hardcode $R$ but when $n$ is unknown this becomes problematic.
Problematic because we need to find a coprime, large number to an arbitrary $n$. 
There are possible solutions to this though, if we split $n$ into two cases:
1. If $n \equiv 1 \mod 2$, we could simply choose $R = 2^{\log_{2}(n)+1}$
2. If $n \equiv 0 \mod 2$, this is not really clear but [Montgomery Reduction With Even Modulus](https://cetinkayakoc.net/docs/j34.pdf) proposes a solution using [The Chinese Remainder Theorem](https://en.wikipedia.org/wiki/Chinese_remainder_theorem) but of course we would have to go and implement it.

Maybe there are more solutions with Montgomery but I have not found them.

## Barret
An alternative to Montgomery's is the [Barret Reduction](https://www.nayuki.io/page/barrett-reduction-algorithm).
Barret still needs to precompute 2 constants: $k$ such that $2^{k} \gt n$ and $r = \frac{4^k}{n}$.
The election of $k$ can be done simply taking $k$ = $log_{2}(n)$ which can be done through [shifts](https://stackoverflow.com/questions/14767308/how-to-compute-log-base-2-using-bitwise-operators).
$r$ can also be computed with shifts and a division since $4^{k} = 2^{2k} = 1 \gg 2k$.
Also, as an advantage, the barret reduction does not need a special form like Montgomery's form 
when operating.

## Useful links:
- [Montgomery arithmetic from a software perspective](https://eprint.iacr.org/2017/1057.pdf)
- [Montgomery reduction with even modulus](https://cetinkayakoc.net/docs/j34.pdf)
- [Comparison of three modular reduction functions](https://lirias.kuleuven.be/retrieve/333369)
- [Algorithmica's chapter on Montgomery](https://en.algorithmica.org/hpc/number-theory/montgomery/)

**Comment by ilitteri** [comment]
Closed as the research finished.
